Cloud bastion
Otus-DevOps-2020-08/asurygin_infra pull request #6
Opened 2020-09-17 15:34 UTC by asurygin

# Выполнено ДЗ №5

 - [ x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
Запуск виртуальных машин bastion и someinternalhost
Подключение напрямую -J
Подключение через ProxyJump
Настроен Pritunl VPN

## Как запустить проект:
перейти

## Как проверить работоспособность:
 Перейти по ссылке http://84.201.176.192

## PR checklist
 - [ x] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2020-09-18 05:38 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Стоит проверить файл конфигурации для овпн, что-то он отображается как бинарь. Вполне возможно из-за этого и проблемы.

2020-09-18 05:38 UTC, mrgreyves commented on README.md
> +alias someinternalhost='ssh  -i ~/.ssh/id_rsa -AJ  appuser@84.201.141.84 appuser@10.129.0.17'
Стоило попробовать создать конфиг для ssh, вариант с alias тоже рабочий =)

2020-09-21 16:12 UTC, asurygin commented on README.md
> +alias someinternalhost='ssh  -i ~/.ssh/id_rsa -AJ  appuser@84.201.141.84 appuser@10.129.0.17'
В дз не уточнялось)

2020-09-21 16:44 UTC, mrgreyves commented on README.md
> +alias someinternalhost='ssh  -i ~/.ssh/id_rsa -AJ  appuser@84.201.141.84 appuser@10.129.0.17'
Это просто рекомендация =)

2020-09-21 16:44 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-09-21 19:41 UTC, asurygin commented
merge cloud-bastion > master

2020-09-21 19:42 UTC, merged